Каркас ДевОпс
Ukrainian-IT-Community/ukrainian-it-guidlines pull request #4
Opened 2022-04-07 17:59 UTC by slapaic

Зроблений каркас ДевОпс-у українською з посиланнями

2022-04-07 18:18 UTC, VolodymyrBalamut requested changes
Треба обговорити питання стосовно того, чи варто додавати цю картинку у наш репозиторій. Чи не буде це порушувати авторські права roadmap.sh.

2022-04-07 18:18 UTC, VolodymyrBalamut commented on docs/devops/orig-tegs.md
> +# DevOps
Можеш, будь ласка, розповісти для чого використовується цей файл?

2022-04-07 18:22 UTC, slapaic commented on docs/devops/orig-tegs.md
> +# DevOps
Оригінальний текст на етапі переводи, поки він не буде ухвалений. Потім видалю, він виключно для моєю та перевіряючого зручності

2022-04-08 07:28 UTC, VolodymyrBalamut approved these changes

2022-04-08 07:29 UTC, VolodymyrBalamut approved these changes

2022-04-08 07:31 UTC, merged